version: '3.8'

services:
  wordcloud-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=development
    # Добавляем зависимость от сети, если необходимо
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
